Repository BoostGSoC19/astronomy, pull requests merged in 2019-08, with the labels that each got.

#64 Error solved in `value()` in `card.hpp`
  include/boost/astronomy/io/card.hpp
Labels: bug-fix

#70 Errors corrected in cartesian_diff and cartesian_rep
  include/boost/astronomy/coordinate/cartesian_differential.hpp
  include/boost/astronomy/coordinate/cartesian_representation.hpp
Labels: bug-fix

#69 `enum bitpix` changed to `enum class`
  .editorconfig
  include/boost/astronomy/io/bitpix.hpp
  include/boost/astronomy/io/card.hpp
  include/boost/astronomy/io/extension_hdu.hpp
  include/boost/astronomy/io/fits.hpp
  include/boost/astronomy/io/hdu.hpp
  include/boost/astronomy/io/image.hpp
  include/boost/astronomy/io/image_extension.hpp
  include/boost/astronomy/io/primary_hdu.hpp
Labels: enhancement, good first issue

#77 Irregular behaviour in fits file reading resolved
  include/boost/astronomy/io/primary_hdu.hpp
Labels: bug-fix

#78 Correction in `make_cartesian_differential`
  include/boost/astronomy/coordinate/spherical_coslat_differential.hpp
Labels: bug-fix

#74 Added test cases for cartesian_representation and cartesian_differential
  test/coordinate/CMakeLists.txt
  test/coordinate/Jamfile
  test/coordinate/cartesian_differential.cpp
  test/coordinate/cartesian_representation.cpp
  test/coordinate/differential.cpp
  test/coordinate/representation.cpp
Labels: test

#83 Added tests for spherical_representation and spherical_differential
  test/coordinate/CMakeLists.txt
  test/coordinate/Jamfile
  test/coordinate/spherical_differential.cpp
  test/coordinate/spherical_representation.cpp
Labels: gsoc19, test

#85 `table_extension`, `column`, `column_data` classes added
  include/boost/astronomy/exception/fits_exception.hpp
  include/boost/astronomy/io/column.hpp
  include/boost/astronomy/io/column_data.hpp
  include/boost/astronomy/io/extension_hdu.hpp
  include/boost/astronomy/io/hdu.hpp
  include/boost/astronomy/io/table_extension.hpp
Labels: enhancement, gsoc19
