Repository BoostGSoC19/astronomy, pull requests merged in 2019-09, with the labels that each got.

#81 Updated the existing documentation
  doc/tutorials/coordinate/astronomical_coordinate.md
  doc/tutorials/coordinate/astronomical_coordinate_operation.md
  doc/tutorials/coordinate/coordinate_conversion.md
  doc/tutorials/coordinate/coordinate_point.md
  doc/tutorials/coordinate/euclidean_coordinate.md
  doc/tutorials/coordinate/motion.md
  doc/tutorials/coordinate/vector_operation.md
  doc/tutorials/index.md
Labels: documentation, gsoc19

#91 missing `const` qualifier added `naxis` mathod of `hdu`
  include/boost/astronomy/io/hdu.hpp
Labels: bug-fix

#93 `get_data` method overloaded to return the reference
  include/boost/astronomy/io/column.hpp
  include/boost/astronomy/io/column_data.hpp
Labels: bug-fix, enhancement

#92 created `binary_table` parser
  include/boost/astronomy/io/binary_table.hpp
Labels: enhancement, gsoc19

#13 Astronomical length units created and alias provided
  include/boost/astronomy/units/length.hpp
  test/CMakeLists.txt
  test/Jamfile
  test/header/CMakeLists.txt
  test/header/Jamfile
  test/units/CMakeLists.txt
  test/units/Jamfile
  test/units/length.cpp
Labels: enhancement, gsoc19

#84 Created parser for ASCII_table extension
  include/boost/astronomy/io/ascii_table.hpp
  include/boost/astronomy/io/fits.hpp
Labels: enhancement, gsoc19

#96 Removed `ASTRONOMY_FIND_BOOST` option
  CMakeLists.txt
Labels: config
