Repository BoostGSoC19/astronomy, pull requests merged in 2019-07, with the labels that each got.

#24 Integrating spherical_equatorial_differential.hpp with units. Closes #19
  include/boost/astronomy/coordinate/spherical_equatorial_differential.hpp
Labels: enhancement, gsoc19

#25 Integrated spherical_equatorial_representation with units. This closes #23
  include/boost/astronomy/coordinate/spherical_equatorial_representation.hpp
Labels: enhancement, gsoc19

#27 Integrated units with spherical_coslat_differential. This closes #22
  include/boost/astronomy/coordinate/spherical_coslat_differential.hpp
Labels: enhancement, gsoc19

#26 Merged the make functions where argument is other differential/representation
  include/boost/astronomy/coordinate/spherical_differential.hpp
  include/boost/astronomy/coordinate/spherical_representation.hpp
Labels: enhancement, gsoc19

#30 Project configured for boost build
  Jamfile
  test/Jamfile
Labels: enhancement

#29 test.cpp removed
  test/CMakeLists.txt
  test/differential.cpp
  test/representation.cpp
  test/test.cpp
Labels: bug-fix

#31 Configured travis CI
  .travis.yml
  ci/travis/bdde.sh
  ci/travis/build.sh
  ci/travis/codecov.sh
  ci/travis/coverity.sh
  ci/travis/cppcheck.sh
  ci/travis/enforce.sh
  ci/travis/install.sh
  ci/travis/intelicc.cfg
  ci/travis/intelicc.sh
  ci/travis/valgrind.sh
Labels: enhancement

#32 Configured azure-pipeline
  azure-pipelines.yml
  ci/azure-pipelines/build.sh
  ci/azure-pipelines/enforce.sh
  ci/azure-pipelines/install.bat
  ci/azure-pipelines/install.sh
Labels: enhancement

#34 Error in make_spherical_representation function resolved
  include/boost/astronomy/coordinate/spherical_representation.hpp
Labels: bug-fix

#35 Configured AppVeyor
  README.md
  appveyor.yml
  ci/azure-pipelines/build.sh
  ci/azure-pipelines/enforce.sh
  ci/azure-pipelines/install.bat
  ci/azure-pipelines/install.sh
  ci/travis/bdde.sh
  ci/travis/build.sh
  ci/travis/codecov.sh
  ci/travis/coverity.sh
  ci/travis/cppcheck.sh
  ci/travis/enforce.sh
  ci/travis/install.sh
  ci/travis/intelicc.cfg
  ci/travis/intelicc.sh
  ci/travis/valgrind.sh
Labels: enhancement

#52 Removed Codecov config from CIs
  .travis.yml
  azure-pipelines.yml
Labels: bug-fix

#37 `base_frame` integrated with units
  include/boost/astronomy/coordinate/base_frame.hpp
Labels: enhancement, gsoc19

#33 Integrated base_equatorial_frame.hpp with units.
  include/boost/astronomy/coordinate/base_equatorial_frame.hpp
Labels: enhancement, gsoc19

#39 Integrated base_ecliptic_frame with units
  include/boost/astronomy/coordinate/base_ecliptic_frame.hpp
Labels: enhancement, gsoc19

#42 Integrated icrs.hpp with units
  include/boost/astronomy/coordinate/icrs.hpp
Labels: enhancement, gsoc19

#43 Integrated cirs.hpp with units
  include/boost/astronomy/coordinate/cirs.hpp
Labels: enhancement, gsoc19

#47 Integrated heliocentric.hpp with units
  include/boost/astronomy/coordinate/heliocentric.hpp
Labels: enhancement, gsoc19

#46 Integrated geocentric.hpp with units
  include/boost/astronomy/coordinate/geocentric.hpp
Labels: enhancement, gsoc19

#51 Integrated galactic.hpp with units
  include/boost/astronomy/coordinate/galactic.hpp
Labels: enhancement, gsoc19

#50 Supergalactic system integrated with boost::units
  include/boost/astronomy/coordinate/supergalactic.hpp
Labels: enhancement, gsoc19

#54 Alt-Az system integrated with boost::units
  include/boost/astronomy/coordinate/alt_az.hpp
Labels: enhancement, gsoc19

#58 Corrections in `alt_az.hpp` and `base_frame.hpp`
  include/boost/astronomy/coordinate/alt_az.hpp
  include/boost/astronomy/coordinate/base_frame.hpp
Labels: bug-fix

#59 Correction in arithmetic.hpp
  include/boost/astronomy/coordinate/arithmetic.hpp
Labels: bug-fix

#63 `is_base_frame_of` struct added
  include/boost/astronomy/detail/is_base_template_of.hpp
Labels: bug-fix

#62 Integrated sky_point.hpp with units
  include/boost/astronomy/coordinate/sky_point.hpp
Labels: enhancement, gsoc19
