Repository BoostGSoC19/astronomy, pull requests merged in 2020-05, with the labels that each got.

#143 Completed Documentation For FITS module
  include/boost/astronomy/io/ascii_table.hpp
  include/boost/astronomy/io/binary_table.hpp
  include/boost/astronomy/io/bitpix.hpp
  include/boost/astronomy/io/card.hpp
  include/boost/astronomy/io/column.hpp
  include/boost/astronomy/io/column_data.hpp
  include/boost/astronomy/io/extension_hdu.hpp
  include/boost/astronomy/io/fits.hpp
  include/boost/astronomy/io/hdu.hpp
  include/boost/astronomy/io/image.hpp
  include/boost/astronomy/io/image_extension.hpp
  include/boost/astronomy/io/primary_hdu.hpp
  include/boost/astronomy/io/table_extension.hpp
Labels: documentation

#148 Modified copyright information to be shorter
  include/boost/astronomy/coordinate/arithmetic.hpp
  include/boost/astronomy/coordinate/coord_sys/alt_az.hpp
  include/boost/astronomy/coordinate/coord_sys/coordinate.hpp
  include/boost/astronomy/coordinate/coord_sys/galactic.hpp
  include/boost/astronomy/coordinate/coord_sys/geocentric.hpp
  include/boost/astronomy/coordinate/coord_sys/heliocentric.hpp
  include/boost/astronomy/coordinate/coord_sys/supergalactic.hpp
  include/boost/astronomy/coordinate/diff/base_differential.hpp
  include/boost/astronomy/coordinate/diff/cartesian_differential.hpp
  include/boost/astronomy/coordinate/diff/differential.hpp
  include/boost/astronomy/coordinate/diff/spherical_coslat_differential.hpp
  include/boost/astronomy/coordinate/diff/spherical_differential.hpp
  include/boost/astronomy/coordinate/diff/spherical_equatorial_differential.hpp
  include/boost/astronomy/coordinate/io/io.hpp
  include/boost/astronomy/coordinate/ref_frame/base_ecliptic_frame.hpp
  include/boost/astronomy/coordinate/ref_frame/base_equatorial_frame.hpp
  include/boost/astronomy/coordinate/ref_frame/base_frame.hpp
  include/boost/astronomy/coordinate/ref_frame/cirs.hpp
  include/boost/astronomy/coordinate/ref_frame/frame.hpp
  include/boost/astronomy/coordinate/ref_frame/icrs.hpp
  include/boost/astronomy/coordinate/rep/base_representation.hpp
  include/boost/astronomy/coordinate/rep/cartesian_representation.hpp
  include/boost/astronomy/coordinate/rep/representation.hpp
  include/boost/astronomy/coordinate/rep/spherical_equatorial_representation.hpp
  include/boost/astronomy/coordinate/rep/spherical_representation.hpp
  include/boost/astronomy/coordinate/sky_point.hpp
  include/boost/astronomy/detail/is_base_template_of.hpp
  include/boost/astronomy/exception/fits_exception.hpp
  include/boost/astronomy/io/ascii_table.hpp
  include/boost/astronomy/io/binary_table.hpp
  include/boost/astronomy/io/bitpix.hpp
  include/boost/astronomy/io/card.hpp
  include/boost/astronomy/io/column.hpp
  include/boost/astronomy/io/column_data.hpp
  include/boost/astronomy/io/extension_hdu.hpp
  include/boost/astronomy/io/fits.hpp
  include/boost/astronomy/io/hdu.hpp
  include/boost/astronomy/io/image.hpp
  include/boost/astronomy/io/image_extension.hpp
  include/boost/astronomy/io/primary_hdu.hpp
  include/boost/astronomy/io/table_extension.hpp
  include/boost/astronomy/units/length.hpp
  test/coordinate/cartesian_differential.cpp
  test/coordinate/cartesian_representation.cpp
  test/coordinate/spherical_differential.cpp
  test/coordinate/spherical_equatorial_differential.cpp
  test/coordinate/spherical_equatorial_representation.cpp
  test/coordinate/spherical_representation.cpp
  test/header/main.cpp
  test/units/length.cpp
Labels: documentation

#149 Added clang-format config file
  .clang-format
Labels: config

#147 Bug Fixes And Refactoring in FITS Module
  include/boost/astronomy/io/ascii_table.hpp
  include/boost/astronomy/io/binary_table.hpp
  include/boost/astronomy/io/card.hpp
  include/boost/astronomy/io/column.hpp
  include/boost/astronomy/io/column_data.hpp
  include/boost/astronomy/io/extension_hdu.hpp
  include/boost/astronomy/io/hdu.hpp
  include/boost/astronomy/io/image_extension.hpp
  include/boost/astronomy/io/table_extension.hpp
Labels: enhancement
